// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/base/files/delete/{id}": {
            "delete": {
                "description": "Deletes a file by its ID",
                "tags": [
                    "01 - Base (internal)"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/files/id/{id}": {
            "get": {
                "description": "Downloads a file by its old Cumulus ID",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "01 - Base (internal)"
                ],
                "summary": "Download a file by old ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Old Cumulus ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/files/info/{id}": {
            "get": {
                "description": "Get detailed information about a file by its old Cumulus ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "01 - Base (internal)"
                ],
                "summary": "Get file info by old ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Old Cumulus ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include base64 content",
                        "name": "extended",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FileInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns OK if service is healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04 - System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v2/files/id/{CumulusID}": {
            "get": {
                "description": "Downloads a file by its old CumulusID",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "02 - Files"
                ],
                "summary": "Download a file by old CumulusID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Old CumulusID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/files/info/{FileGUID}": {
            "get": {
                "description": "Get detailed information about a file",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02 - Files"
                ],
                "summary": "Get file info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include base64 content",
                        "name": "extended",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FileInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/files/upload": {
            "post": {
                "description": "Uploads a file to the storage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02 - Files"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tags like array of string or coma separated strings",
                        "name": "tags",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Legacy ID",
                        "name": "old_cumulus_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Validity period (e.g. '1 day', '2 months')",
                        "name": "validity",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "413": {
                        "description": "File too large",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/files/{FileGUID}": {
            "get": {
                "description": "Downloads a file by its GUID",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "02 - Files"
                ],
                "summary": "Download a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File GUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/images/{uuid}": {
            "get": {
                "description": "Downloads original image or resized variant (thumb, sm, md, lg). For PDF files, generates thumbnail.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "03 - Images"
                ],
                "summary": "Get image or image variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Not an image or PDF",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/images/{uuid}/lg": {
            "get": {
                "description": "Downloads original image or resized variant (thumb, sm, md, lg). For PDF files, generates thumbnail.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "03 - Images"
                ],
                "summary": "Get image or image variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Not an image or PDF",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/images/{uuid}/md": {
            "get": {
                "description": "Downloads original image or resized variant (thumb, sm, md, lg). For PDF files, generates thumbnail.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "03 - Images"
                ],
                "summary": "Get image or image variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Not an image or PDF",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/images/{uuid}/sm": {
            "get": {
                "description": "Downloads original image or resized variant (thumb, sm, md, lg). For PDF files, generates thumbnail.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "03 - Images"
                ],
                "summary": "Get image or image variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Not an image or PDF",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/images/{uuid}/thumb": {
            "get": {
                "description": "Downloads original image or resized variant (thumb, sm, md, lg). For PDF files, generates thumbnail.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "03 - Images"
                ],
                "summary": "Get image or image variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Not an image or PDF",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.FileInfo": {
            "type": "object",
            "properties": {
                "blob_id": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "compression_alg": {
                    "type": "string"
                },
                "content": {
                    "description": "Base64 encoded",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "old_cumulus_id": {
                    "type": "integer"
                },
                "size_compressed": {
                    "type": "integer"
                },
                "size_raw": {
                    "type": "integer"
                },
                "subtype": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Internal endpoints for backward compatibility with old Cumulus ID system",
            "name": "01 - Base (internal)"
        },
        {
            "description": "Main file operations - upload, download, metadata, delete",
            "name": "02 - Files"
        },
        {
            "description": "Image processing endpoints - thumbnails, previews, transformations",
            "name": "03 - Images"
        },
        {
            "description": "System endpoints - health checks, metrics",
            "name": "04 - System"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cumulus3",
	Description:      "High-performance distributed object storage server in Go (SeaweedFS architecture). Features smart deduplication (BLAKE2b), adaptive Zstd compression, SQLite (WAL) metadata, and native Prometheus metrics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
